### ISSUE TITLE
Using while loop thrown a http response is unavailable (maybe it has been ended or detached) in events server

### ISSUE THREAD

**Issue by ljfreelancer88** [james2doyle/swoole-examples#1]
Hi, first of all thank you for all the Swoole resources. Just a quick question regarding events server. How can I control the time, let say every 1 or 2 seconds, it will publish events because the given example published every 5sec. I did try to wrap a do while loop but I got PHP Warning issue `Swoole\Http\Response::end(): http response is unavailable (maybe it has been ended or detached)`

**Comment by james2doyle** [comment]
@ljfreelancer88 I finally got around to updating the server sent event example to work now: https://github.com/james2doyle/swoole-examples/commit/70e2f8d35841f2540adae3437b10b3a9a3c3dab9
